version: '2.0'
services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    container_name: nginx-container
    links:
      - phpfpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - project

  phpfpm:
    build: ./php/
    ports:
      - 9000:9000
    container_name: phpfpm-container
    links:
      - mysql
    volumes:
      - ./php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php
    volumes_from:
      - project
    extra_hosts:
      - vdolganov.docker.local:192.168.43.84

  project:
    image: alpine:latest
    container_name: project-container
    volumes:
      - ../project:/var/www/project
    command: "true"

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: mysql-container
    volumes:
      - ./databases:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: vadim
      MYSQL_PASSWORD: 123456Q

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8084:80
    container_name: phpmyadmin-container
    links:
      - phpfpm
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
